/*
 * **************************************************-
 * ingrid-utils
 * ==================================================
 * Copyright (C) 2014 - 2023 wemove digital solutions GmbH
 * ==================================================
 * Licensed under the EUPL, Version 1.1 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 * 
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 * 
 * http://ec.europa.eu/idabc/eupl5
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 * **************************************************#
 */
package de.ingrid.utils.udk;

import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * This class contains the MOST RECENT IGC Country Codelist and helper functions.
 */
public class UtilsCountryCodelist {

	/** Syslist ID of country codelist. */
	static public int COUNTRY_SYSLIST_ID = 6200;

	public static final Integer COUNTRY_KEY_GERMANY = 276;
	public static final Integer COUNTRY_KEY_GBR = 826;

	/** MAP: syslist with german names of countries <ISO country code, german name of country> */
	static public HashMap<Integer, String> countryCodelist_de = new LinkedHashMap<Integer, String>();
	static {
		countryCodelist_de.put(Integer.valueOf(4), "Afghanistan");
		countryCodelist_de.put(Integer.valueOf(818), "\u00c4gypten");
		countryCodelist_de.put(Integer.valueOf(248), "\u00c5land");
		countryCodelist_de.put(Integer.valueOf(8), "Albanien");
		countryCodelist_de.put(Integer.valueOf(12), "Algerien");
		countryCodelist_de.put(Integer.valueOf(850), "Amerikanische Jungferninseln");
		countryCodelist_de.put(Integer.valueOf(16), "Amerikanisch-Samoa");
		countryCodelist_de.put(Integer.valueOf(20), "Andorra");
		countryCodelist_de.put(Integer.valueOf(24), "Angola");
		countryCodelist_de.put(Integer.valueOf(660), "Anguilla");
		countryCodelist_de.put(Integer.valueOf(10), "Antarktis");
		countryCodelist_de.put(Integer.valueOf(28), "Antigua und Barbuda");
		countryCodelist_de.put(Integer.valueOf(226), "\u00c4quatorialguinea");
		countryCodelist_de.put(Integer.valueOf(32), "Argentinien");
		countryCodelist_de.put(Integer.valueOf(51), "Armenien");
		countryCodelist_de.put(Integer.valueOf(533), "Aruba");
		countryCodelist_de.put(Integer.valueOf(31), "Aserbaidschan");
		countryCodelist_de.put(Integer.valueOf(231), "\u00c4thiopien");
		countryCodelist_de.put(Integer.valueOf(36), "Australien");
		countryCodelist_de.put(Integer.valueOf(44), "Bahamas");
		countryCodelist_de.put(Integer.valueOf(48), "Bahrain");
		countryCodelist_de.put(Integer.valueOf(50), "Bangladesch");
		countryCodelist_de.put(Integer.valueOf(52), "Barbados");
		countryCodelist_de.put(Integer.valueOf(112), "Belarus (Wei\u00dfrussland)");
		countryCodelist_de.put(Integer.valueOf(56), "Belgien");
		countryCodelist_de.put(Integer.valueOf(84), "Belize");
		countryCodelist_de.put(Integer.valueOf(204), "Benin");
		countryCodelist_de.put(Integer.valueOf(60), "Bermuda");
		countryCodelist_de.put(Integer.valueOf(64), "Bhutan");
		countryCodelist_de.put(Integer.valueOf(68), "Bolivien");
		countryCodelist_de.put(Integer.valueOf(70), "Bosnien und Herzegowina");
		countryCodelist_de.put(Integer.valueOf(72), "Botswana");
		countryCodelist_de.put(Integer.valueOf(74), "Bouvetinsel");
		countryCodelist_de.put(Integer.valueOf(76), "Brasilien");
		countryCodelist_de.put(Integer.valueOf(92), "Britische Jungferninseln");
		countryCodelist_de.put(Integer.valueOf(86), "Britisches Territorium im Indischen Ozean");
		countryCodelist_de.put(Integer.valueOf(96), "Brunei Darussalam");
		countryCodelist_de.put(Integer.valueOf(100), "Bulgarien");
		countryCodelist_de.put(Integer.valueOf(854), "Burkina Faso");
		countryCodelist_de.put(Integer.valueOf(108), "Burundi");
		countryCodelist_de.put(Integer.valueOf(152), "Chile");
		countryCodelist_de.put(Integer.valueOf(156), "China, Volksrepublik");
		countryCodelist_de.put(Integer.valueOf(184), "Cookinseln");
		countryCodelist_de.put(Integer.valueOf(188), "Costa Rica");
		countryCodelist_de.put(Integer.valueOf(384), "C\u00f4te d'Ivoire (Elfenbeink\u00fcste)");
		countryCodelist_de.put(Integer.valueOf(208), "D\u00e4nemark");
		countryCodelist_de.put(Integer.valueOf(276), "Deutschland");
		countryCodelist_de.put(Integer.valueOf(212), "Dominica");
		countryCodelist_de.put(Integer.valueOf(214), "Dominikanische Republik");
		countryCodelist_de.put(Integer.valueOf(262), "Dschibuti");
		countryCodelist_de.put(Integer.valueOf(218), "Ecuador");
		countryCodelist_de.put(Integer.valueOf(222), "El Salvador");
		countryCodelist_de.put(Integer.valueOf(232), "Eritrea");
		countryCodelist_de.put(Integer.valueOf(233), "Estland");
		countryCodelist_de.put(Integer.valueOf(238), "Falklandinseln");
		countryCodelist_de.put(Integer.valueOf(234), "F\u00e4r\u00f6er");
		countryCodelist_de.put(Integer.valueOf(242), "Fidschi");
		countryCodelist_de.put(Integer.valueOf(246), "Finnland");
		countryCodelist_de.put(Integer.valueOf(250), "Frankreich");
		countryCodelist_de.put(Integer.valueOf(260), "Franz\u00f6sische S\u00fcd- und Antarktisgebiete");
		countryCodelist_de.put(Integer.valueOf(254), "Franz\u00f6sisch-Guayana");
		countryCodelist_de.put(Integer.valueOf(258), "Franz\u00f6sisch-Polynesien");
		countryCodelist_de.put(Integer.valueOf(266), "Gabun");
		countryCodelist_de.put(Integer.valueOf(270), "Gambia");
		countryCodelist_de.put(Integer.valueOf(268), "Georgien");
		countryCodelist_de.put(Integer.valueOf(288), "Ghana");
		countryCodelist_de.put(Integer.valueOf(292), "Gibraltar");
		countryCodelist_de.put(Integer.valueOf(308), "Grenada");
		countryCodelist_de.put(Integer.valueOf(300), "Griechenland");
		countryCodelist_de.put(Integer.valueOf(304), "Gr\u00f6nland");
		countryCodelist_de.put(Integer.valueOf(312), "Guadeloupe");
		countryCodelist_de.put(Integer.valueOf(316), "Guam");
		countryCodelist_de.put(Integer.valueOf(320), "Guatemala");
		countryCodelist_de.put(Integer.valueOf(831), "Guernsey (Kanalinsel)");
		countryCodelist_de.put(Integer.valueOf(324), "Guinea");
		countryCodelist_de.put(Integer.valueOf(624), "Guinea-Bissau");
		countryCodelist_de.put(Integer.valueOf(328), "Guyana");
		countryCodelist_de.put(Integer.valueOf(332), "Haiti");
		countryCodelist_de.put(Integer.valueOf(334), "Heard- und McDonald-Inseln");
		countryCodelist_de.put(Integer.valueOf(340), "Honduras");
		countryCodelist_de.put(Integer.valueOf(344), "Hongkong");
		countryCodelist_de.put(Integer.valueOf(356), "Indien");
		countryCodelist_de.put(Integer.valueOf(360), "Indonesien");
		countryCodelist_de.put(Integer.valueOf(833), "Insel Man");
		countryCodelist_de.put(Integer.valueOf(368), "Irak");
		countryCodelist_de.put(Integer.valueOf(364), "Iran, Islamische Republik");
		countryCodelist_de.put(Integer.valueOf(372), "Irland");
		countryCodelist_de.put(Integer.valueOf(352), "Island");
		countryCodelist_de.put(Integer.valueOf(376), "Israel");
		countryCodelist_de.put(Integer.valueOf(380), "Italien");
		countryCodelist_de.put(Integer.valueOf(388), "Jamaika");
		countryCodelist_de.put(Integer.valueOf(392), "Japan");
		countryCodelist_de.put(Integer.valueOf(887), "Jemen");
		countryCodelist_de.put(Integer.valueOf(832), "Jersey (Kanalinsel)");
		countryCodelist_de.put(Integer.valueOf(400), "Jordanien");
		countryCodelist_de.put(Integer.valueOf(136), "Kaimaninseln");
		countryCodelist_de.put(Integer.valueOf(116), "Kambodscha");
		countryCodelist_de.put(Integer.valueOf(120), "Kamerun");
		countryCodelist_de.put(Integer.valueOf(124), "Kanada");
		countryCodelist_de.put(Integer.valueOf(132), "Kap Verde");
		countryCodelist_de.put(Integer.valueOf(398), "Kasachstan");
		countryCodelist_de.put(Integer.valueOf(634), "Katar");
		countryCodelist_de.put(Integer.valueOf(404), "Kenia");
		countryCodelist_de.put(Integer.valueOf(417), "Kirgisistan");
		countryCodelist_de.put(Integer.valueOf(296), "Kiribati");
		countryCodelist_de.put(Integer.valueOf(166), "Kokosinseln");
		countryCodelist_de.put(Integer.valueOf(170), "Kolumbien");
		countryCodelist_de.put(Integer.valueOf(174), "Komoren");
		countryCodelist_de.put(Integer.valueOf(180), "Kongo, Demokratische Republik (ehem. Zaire)");
		countryCodelist_de.put(Integer.valueOf(408), "Korea, Demokratische Volksrepublik (Nordkorea)");
		countryCodelist_de.put(Integer.valueOf(410), "Korea, Republik (S\u00fcdkorea)");
		countryCodelist_de.put(Integer.valueOf(191), "Kroatien");
		countryCodelist_de.put(Integer.valueOf(192), "Kuba");
		countryCodelist_de.put(Integer.valueOf(414), "Kuwait");
		countryCodelist_de.put(Integer.valueOf(418), "Laos, Demokratische Volksrepublik");
		countryCodelist_de.put(Integer.valueOf(426), "Lesotho");
		countryCodelist_de.put(Integer.valueOf(428), "Lettland");
		countryCodelist_de.put(Integer.valueOf(422), "Libanon");
		countryCodelist_de.put(Integer.valueOf(430), "Liberia");
		countryCodelist_de.put(Integer.valueOf(434), "Libysch-Arabische Dschamahirija (Libyen)");
		countryCodelist_de.put(Integer.valueOf(438), "Liechtenstein");
		countryCodelist_de.put(Integer.valueOf(440), "Litauen");
		countryCodelist_de.put(Integer.valueOf(442), "Luxemburg");
		countryCodelist_de.put(Integer.valueOf(446), "Macao");
		countryCodelist_de.put(Integer.valueOf(450), "Madagaskar");
		countryCodelist_de.put(Integer.valueOf(454), "Malawi");
		countryCodelist_de.put(Integer.valueOf(458), "Malaysia");
		countryCodelist_de.put(Integer.valueOf(462), "Malediven");
		countryCodelist_de.put(Integer.valueOf(466), "Mali");
		countryCodelist_de.put(Integer.valueOf(470), "Malta");
		countryCodelist_de.put(Integer.valueOf(504), "Marokko");
		countryCodelist_de.put(Integer.valueOf(584), "Marshallinseln");
		countryCodelist_de.put(Integer.valueOf(474), "Martinique");
		countryCodelist_de.put(Integer.valueOf(478), "Mauretanien");
		countryCodelist_de.put(Integer.valueOf(480), "Mauritius");
		countryCodelist_de.put(Integer.valueOf(175), "Mayotte");
		countryCodelist_de.put(Integer.valueOf(807), "Mazedonien, ehem. jugoslawische Republik");
		countryCodelist_de.put(Integer.valueOf(484), "Mexiko");
		countryCodelist_de.put(Integer.valueOf(583), "Mikronesien");
		countryCodelist_de.put(Integer.valueOf(498), "Moldawien (Republik Moldau)");
		countryCodelist_de.put(Integer.valueOf(492), "Monaco");
		countryCodelist_de.put(Integer.valueOf(496), "Mongolei");
		countryCodelist_de.put(Integer.valueOf(499), "Montenegro");
		countryCodelist_de.put(Integer.valueOf(500), "Montserrat");
		countryCodelist_de.put(Integer.valueOf(508), "Mosambik");
		countryCodelist_de.put(Integer.valueOf(104), "Myanmar (Burma)");
		countryCodelist_de.put(Integer.valueOf(516), "Namibia");
		countryCodelist_de.put(Integer.valueOf(520), "Nauru");
		countryCodelist_de.put(Integer.valueOf(524), "Nepal");
		countryCodelist_de.put(Integer.valueOf(540), "Neukaledonien");
		countryCodelist_de.put(Integer.valueOf(554), "Neuseeland");
		countryCodelist_de.put(Integer.valueOf(558), "Nicaragua");
		countryCodelist_de.put(Integer.valueOf(528), "Niederlande");
		countryCodelist_de.put(Integer.valueOf(530), "Niederl\u00e4ndische Antillen");
		countryCodelist_de.put(Integer.valueOf(562), "Niger");
		countryCodelist_de.put(Integer.valueOf(566), "Nigeria");
		countryCodelist_de.put(Integer.valueOf(570), "Niue");
		countryCodelist_de.put(Integer.valueOf(580), "N\u00f6rdliche Marianen");
		countryCodelist_de.put(Integer.valueOf(574), "Norfolkinsel");
		countryCodelist_de.put(Integer.valueOf(578), "Norwegen");
		countryCodelist_de.put(Integer.valueOf(512), "Oman");
		countryCodelist_de.put(Integer.valueOf(40),	 "\u00d6sterreich");
		countryCodelist_de.put(Integer.valueOf(626), "Osttimor (Timor-Leste)");
		countryCodelist_de.put(Integer.valueOf(586), "Pakistan");
		countryCodelist_de.put(Integer.valueOf(275), "Pal\u00e4stinensische Autonomiegebiete");
		countryCodelist_de.put(Integer.valueOf(585), "Palau");
		countryCodelist_de.put(Integer.valueOf(591), "Panama");
		countryCodelist_de.put(Integer.valueOf(598), "Papua-Neuguinea");
		countryCodelist_de.put(Integer.valueOf(600), "Paraguay");
		countryCodelist_de.put(Integer.valueOf(604), "Peru");
		countryCodelist_de.put(Integer.valueOf(608), "Philippinen");
		countryCodelist_de.put(Integer.valueOf(612), "Pitcairninseln");
		countryCodelist_de.put(Integer.valueOf(616), "Polen");
		countryCodelist_de.put(Integer.valueOf(620), "Portugal");
		countryCodelist_de.put(Integer.valueOf(630), "Puerto Rico");
		countryCodelist_de.put(Integer.valueOf(158), "Republik China (Taiwan)");
		countryCodelist_de.put(Integer.valueOf(178), "Republik Kongo");
		countryCodelist_de.put(Integer.valueOf(638), "R\u00e9union");
		countryCodelist_de.put(Integer.valueOf(646), "Ruanda");
		countryCodelist_de.put(Integer.valueOf(642), "Rum\u00e4nien");
		countryCodelist_de.put(Integer.valueOf(643), "Russische F\u00f6deration");
		countryCodelist_de.put(Integer.valueOf(652), "Saint-Barth\u00e9lemy");
		countryCodelist_de.put(Integer.valueOf(663), "Saint-Martin (franz. Teil)");
		countryCodelist_de.put(Integer.valueOf(90),  "Salomonen");
		countryCodelist_de.put(Integer.valueOf(894), "Sambia");
		countryCodelist_de.put(Integer.valueOf(882), "Samoa");
		countryCodelist_de.put(Integer.valueOf(674), "San Marino");
		countryCodelist_de.put(Integer.valueOf(678), "S\u00e3o Tom\u00e9 und Pr\u00edncipe");
		countryCodelist_de.put(Integer.valueOf(682), "Saudi-Arabien");
		countryCodelist_de.put(Integer.valueOf(752), "Schweden");
		countryCodelist_de.put(Integer.valueOf(756), "Schweiz (Confoederatio Helvetica)");
		countryCodelist_de.put(Integer.valueOf(686), "Senegal");
		countryCodelist_de.put(Integer.valueOf(688), "Serbien");
		countryCodelist_de.put(Integer.valueOf(690), "Seychellen");
		countryCodelist_de.put(Integer.valueOf(694), "Sierra Leone");
		countryCodelist_de.put(Integer.valueOf(716), "Simbabwe");
		countryCodelist_de.put(Integer.valueOf(702), "Singapur");
		countryCodelist_de.put(Integer.valueOf(703), "Slowakei");
		countryCodelist_de.put(Integer.valueOf(705), "Slowenien");
		countryCodelist_de.put(Integer.valueOf(706), "Somalia");
		countryCodelist_de.put(Integer.valueOf(724), "Spanien");
		countryCodelist_de.put(Integer.valueOf(144), "Sri Lanka");
		countryCodelist_de.put(Integer.valueOf(654), "St. Helena");
		countryCodelist_de.put(Integer.valueOf(659), "St. Kitts und Nevis");
		countryCodelist_de.put(Integer.valueOf(662), "St. Lucia");
		countryCodelist_de.put(Integer.valueOf(666), "St. Pierre und MiquelonSaint-Pierre und Miquelon");
		countryCodelist_de.put(Integer.valueOf(670), "St. Vincent und die Grenadinen");
		countryCodelist_de.put(Integer.valueOf(710), "S\u00fcdafrika");
		countryCodelist_de.put(Integer.valueOf(736), "Sudan");
		countryCodelist_de.put(Integer.valueOf(239), "S\u00fcdgeorgien und die S\u00fcdlichen Sandwichinseln");
		countryCodelist_de.put(Integer.valueOf(740), "Suriname");
		countryCodelist_de.put(Integer.valueOf(744), "Svalbard und Jan Mayen");
		countryCodelist_de.put(Integer.valueOf(748), "Swasiland");
		countryCodelist_de.put(Integer.valueOf(760), "Syrien, Arabische Republik");
		countryCodelist_de.put(Integer.valueOf(762), "Tadschikistan");
		countryCodelist_de.put(Integer.valueOf(834), "Tansania, Vereinigte Republik");
		countryCodelist_de.put(Integer.valueOf(764), "Thailand");
		countryCodelist_de.put(Integer.valueOf(768), "Togo");
		countryCodelist_de.put(Integer.valueOf(772), "Tokelau");
		countryCodelist_de.put(Integer.valueOf(776), "Tonga");
		countryCodelist_de.put(Integer.valueOf(780), "Trinidad und Tobago");
		countryCodelist_de.put(Integer.valueOf(148), "Tschad");
		countryCodelist_de.put(Integer.valueOf(203), "Tschechische Republik");
		countryCodelist_de.put(Integer.valueOf(788), "Tunesien");
		countryCodelist_de.put(Integer.valueOf(792), "T\u00fcrkei");
		countryCodelist_de.put(Integer.valueOf(795), "Turkmenistan");
		countryCodelist_de.put(Integer.valueOf(796), "Turks- und Caicosinseln");
		countryCodelist_de.put(Integer.valueOf(798), "Tuvalu");
		countryCodelist_de.put(Integer.valueOf(800), "Uganda");
		countryCodelist_de.put(Integer.valueOf(804), "Ukraine");
		countryCodelist_de.put(Integer.valueOf(348), "Ungarn");
		countryCodelist_de.put(Integer.valueOf(581), "United States Minor Outlying Islands");
		countryCodelist_de.put(Integer.valueOf(858), "Uruguay");
		countryCodelist_de.put(Integer.valueOf(860), "Usbekistan");
		countryCodelist_de.put(Integer.valueOf(548), "Vanuatu");
		countryCodelist_de.put(Integer.valueOf(336), "Vatikanstadt");
		countryCodelist_de.put(Integer.valueOf(862), "Venezuela");
		countryCodelist_de.put(Integer.valueOf(784), "Vereinigte Arabische Emirate");
		countryCodelist_de.put(Integer.valueOf(840), "Vereinigte Staaten von Amerika");
		countryCodelist_de.put(Integer.valueOf(826), "Vereinigtes K\u00f6nigreich Gro\u00dfbritannien und Nordirland");
		countryCodelist_de.put(Integer.valueOf(704), "Vietnam");
		countryCodelist_de.put(Integer.valueOf(876), "Wallis und Futuna");
		countryCodelist_de.put(Integer.valueOf(162), "Weihnachtsinsel");
		countryCodelist_de.put(Integer.valueOf(732), "Westsahara");
		countryCodelist_de.put(Integer.valueOf(140), "Zentralafrikanische Republik");
		countryCodelist_de.put(Integer.valueOf(196), "Zypern");													
	}

	/** MAP: syslist with english names of countries <ISO country code, english name of country> */
	static public HashMap<Integer, String> countryCodelist_en = new LinkedHashMap<Integer, String>();
	static {
		countryCodelist_en.put(Integer.valueOf("4"), "Afghanistan");
		countryCodelist_en.put(Integer.valueOf("818"), "Egypt");
		countryCodelist_en.put(Integer.valueOf("248"), "\u00c5land Islands");
		countryCodelist_en.put(Integer.valueOf("8"), "Albania");
		countryCodelist_en.put(Integer.valueOf("12"), "Algeria");
		countryCodelist_en.put(Integer.valueOf("850"), "Virgin Islands, U.S.");
		countryCodelist_en.put(Integer.valueOf("16"), "American Samoa");
		countryCodelist_en.put(Integer.valueOf("20"), "Andorra");
		countryCodelist_en.put(Integer.valueOf("24"), "Angola");
		countryCodelist_en.put(Integer.valueOf("660"), "Anguilla");
		countryCodelist_en.put(Integer.valueOf("10"), "Antarctica");
		countryCodelist_en.put(Integer.valueOf("28"), "Antigua and Barbuda");
		countryCodelist_en.put(Integer.valueOf("226"), "Equatorial Guinea");
		countryCodelist_en.put(Integer.valueOf("32"), "Argentina");
		countryCodelist_en.put(Integer.valueOf("51"), "Armenia");
		countryCodelist_en.put(Integer.valueOf("533"), "Aruba");
		countryCodelist_en.put(Integer.valueOf("31"), "Azerbaijan");
		countryCodelist_en.put(Integer.valueOf("231"), "Ethiopia");
		countryCodelist_en.put(Integer.valueOf("36"), "Australia");
		countryCodelist_en.put(Integer.valueOf("44"), "Bahamas");
		countryCodelist_en.put(Integer.valueOf("48"), "Bahrain");
		countryCodelist_en.put(Integer.valueOf("50"), "Bangladesh");
		countryCodelist_en.put(Integer.valueOf("52"), "Barbados");
		countryCodelist_en.put(Integer.valueOf("112"), "Belarus");
		countryCodelist_en.put(Integer.valueOf("56"), "Belgium");
		countryCodelist_en.put(Integer.valueOf("84"), "Belize");
		countryCodelist_en.put(Integer.valueOf("204"), "Benin");
		countryCodelist_en.put(Integer.valueOf("60"), "Bermuda");
		countryCodelist_en.put(Integer.valueOf("64"), "Bhutan");
		countryCodelist_en.put(Integer.valueOf("68"), "Bolivia, Plurinational State of");
		countryCodelist_en.put(Integer.valueOf("70"), "Bosnia and Herzegovina");
		countryCodelist_en.put(Integer.valueOf("72"), "Botswana");
		countryCodelist_en.put(Integer.valueOf("74"), "Bouvet Island");
		countryCodelist_en.put(Integer.valueOf("76"), "Brazil");
		countryCodelist_en.put(Integer.valueOf("92"), "Virgin Islands, British");
		countryCodelist_en.put(Integer.valueOf("86"), "British Indian Ocean Territory");
		countryCodelist_en.put(Integer.valueOf("96"), "Brunei Darussalam");
		countryCodelist_en.put(Integer.valueOf("100"), "Bulgaria");
		countryCodelist_en.put(Integer.valueOf("854"), "Burkina Faso");
		countryCodelist_en.put(Integer.valueOf("108"), "Burundi");
		countryCodelist_en.put(Integer.valueOf("152"), "Chile");
		countryCodelist_en.put(Integer.valueOf("156"), "China");
		countryCodelist_en.put(Integer.valueOf("184"), "Cook Islands");
		countryCodelist_en.put(Integer.valueOf("188"), "Costa Rica");
		countryCodelist_en.put(Integer.valueOf("384"), "C\u00f4te d'Ivoire");
		countryCodelist_en.put(Integer.valueOf("208"), "Denmark");
		countryCodelist_en.put(Integer.valueOf("276"), "Germany");
		countryCodelist_en.put(Integer.valueOf("212"), "Dominica");
		countryCodelist_en.put(Integer.valueOf("214"), "Dominican Republic");
		countryCodelist_en.put(Integer.valueOf("262"), "Djibouti");
		countryCodelist_en.put(Integer.valueOf("218"), "Ecuador");
		countryCodelist_en.put(Integer.valueOf("222"), "El Salvador");
		countryCodelist_en.put(Integer.valueOf("232"), "Eritrea");
		countryCodelist_en.put(Integer.valueOf("233"), "Estonia");
		countryCodelist_en.put(Integer.valueOf("238"), "Falkland Islands (Malvinas)");
		countryCodelist_en.put(Integer.valueOf("234"), "Faroe Islands");
		countryCodelist_en.put(Integer.valueOf("242"), "Fiji");
		countryCodelist_en.put(Integer.valueOf("246"), "Finland");
		countryCodelist_en.put(Integer.valueOf("250"), "France");
		countryCodelist_en.put(Integer.valueOf("260"), "French Southern Territories");
		countryCodelist_en.put(Integer.valueOf("254"), "French Guiana");
		countryCodelist_en.put(Integer.valueOf("258"), "French Polynesia");
		countryCodelist_en.put(Integer.valueOf("266"), "Gabon");
		countryCodelist_en.put(Integer.valueOf("270"), "Gambia");
		countryCodelist_en.put(Integer.valueOf("268"), "Georgia");
		countryCodelist_en.put(Integer.valueOf("288"), "Ghana");
		countryCodelist_en.put(Integer.valueOf("292"), "Gibraltar");
		countryCodelist_en.put(Integer.valueOf("308"), "Grenada");
		countryCodelist_en.put(Integer.valueOf("300"), "Greece");
		countryCodelist_en.put(Integer.valueOf("304"), "Greenland");
		countryCodelist_en.put(Integer.valueOf("312"), "Guadeloupe");
		countryCodelist_en.put(Integer.valueOf("316"), "Guam");
		countryCodelist_en.put(Integer.valueOf("320"), "Guatemala");
		countryCodelist_en.put(Integer.valueOf("831"), "Guernsey");
		countryCodelist_en.put(Integer.valueOf("324"), "Guinea");
		countryCodelist_en.put(Integer.valueOf("624"), "Guinea-Bissau");
		countryCodelist_en.put(Integer.valueOf("328"), "Guyana");
		countryCodelist_en.put(Integer.valueOf("332"), "Haiti");
		countryCodelist_en.put(Integer.valueOf("334"), "Heard Island and McDonald Islands");
		countryCodelist_en.put(Integer.valueOf("340"), "Honduras");
		countryCodelist_en.put(Integer.valueOf("344"), "Hong Kong");
		countryCodelist_en.put(Integer.valueOf("356"), "India");
		countryCodelist_en.put(Integer.valueOf("360"), "Indonesia");
		countryCodelist_en.put(Integer.valueOf("833"), "Isle of Man");
		countryCodelist_en.put(Integer.valueOf("368"), "Iraq");
		countryCodelist_en.put(Integer.valueOf("364"), "Iran, Islamic Republic of");
		countryCodelist_en.put(Integer.valueOf("372"), "Ireland");
		countryCodelist_en.put(Integer.valueOf("352"), "Iceland");
		countryCodelist_en.put(Integer.valueOf("376"), "Israel");
		countryCodelist_en.put(Integer.valueOf("380"), "Italy");
		countryCodelist_en.put(Integer.valueOf("388"), "Jamaica");
		countryCodelist_en.put(Integer.valueOf("392"), "Japan");
		countryCodelist_en.put(Integer.valueOf("887"), "Yemen");
		countryCodelist_en.put(Integer.valueOf("832"), "Jersey");
		countryCodelist_en.put(Integer.valueOf("400"), "Jordan");
		countryCodelist_en.put(Integer.valueOf("136"), "Cayman Islands");
		countryCodelist_en.put(Integer.valueOf("116"), "Cambodia");
		countryCodelist_en.put(Integer.valueOf("120"), "Cameroon");
		countryCodelist_en.put(Integer.valueOf("124"), "Canada");
		countryCodelist_en.put(Integer.valueOf("132"), "Cape Verde");
		countryCodelist_en.put(Integer.valueOf("398"), "Kazakhstan");
		countryCodelist_en.put(Integer.valueOf("634"), "Qatar");
		countryCodelist_en.put(Integer.valueOf("404"), "Kenya");
		countryCodelist_en.put(Integer.valueOf("417"), "Kyrgyzstan");
		countryCodelist_en.put(Integer.valueOf("296"), "Kiribati");
		countryCodelist_en.put(Integer.valueOf("166"), "Cocos (Keeling) Islands");
		countryCodelist_en.put(Integer.valueOf("170"), "Colombia");
		countryCodelist_en.put(Integer.valueOf("174"), "Comoros");
		countryCodelist_en.put(Integer.valueOf("180"), "Congo, the Democratic Republic of the");
		countryCodelist_en.put(Integer.valueOf("408"), "Korea, Democratic People's Republic of");
		countryCodelist_en.put(Integer.valueOf("410"), "Korea, Republic of");
		countryCodelist_en.put(Integer.valueOf("191"), "Croatia");
		countryCodelist_en.put(Integer.valueOf("192"), "Cuba");
		countryCodelist_en.put(Integer.valueOf("414"), "Kuwait");
		countryCodelist_en.put(Integer.valueOf("418"), "Lao People's Democratic Republic");
		countryCodelist_en.put(Integer.valueOf("426"), "Lesotho");
		countryCodelist_en.put(Integer.valueOf("428"), "Latvia");
		countryCodelist_en.put(Integer.valueOf("422"), "Lebanon");
		countryCodelist_en.put(Integer.valueOf("430"), "Liberia");
		countryCodelist_en.put(Integer.valueOf("434"), "Libyan Arab Jamahiriya");
		countryCodelist_en.put(Integer.valueOf("438"), "Liechtenstein");
		countryCodelist_en.put(Integer.valueOf("440"), "Lithuania");
		countryCodelist_en.put(Integer.valueOf("442"), "Luxembourg");
		countryCodelist_en.put(Integer.valueOf("446"), "Macao");
		countryCodelist_en.put(Integer.valueOf("450"), "Madagascar");
		countryCodelist_en.put(Integer.valueOf("454"), "Malawi");
		countryCodelist_en.put(Integer.valueOf("458"), "Malaysia");
		countryCodelist_en.put(Integer.valueOf("462"), "Maldives");
		countryCodelist_en.put(Integer.valueOf("466"), "Mali");
		countryCodelist_en.put(Integer.valueOf("470"), "Malta");
		countryCodelist_en.put(Integer.valueOf("504"), "Morocco");
		countryCodelist_en.put(Integer.valueOf("584"), "Marshall Islands");
		countryCodelist_en.put(Integer.valueOf("474"), "Martinique");
		countryCodelist_en.put(Integer.valueOf("478"), "Mauritania");
		countryCodelist_en.put(Integer.valueOf("480"), "Mauritius");
		countryCodelist_en.put(Integer.valueOf("175"), "Mayotte");
		countryCodelist_en.put(Integer.valueOf("807"), "Macedonia, the former Yugoslav Republic of");
		countryCodelist_en.put(Integer.valueOf("484"), "Mexico");
		countryCodelist_en.put(Integer.valueOf("583"), "Micronesia, Federated States of");
		countryCodelist_en.put(Integer.valueOf("498"), "Moldova, Republic of");
		countryCodelist_en.put(Integer.valueOf("492"), "Monaco");
		countryCodelist_en.put(Integer.valueOf("496"), "Mongolia");
		countryCodelist_en.put(Integer.valueOf("499"), "Montenegro");
		countryCodelist_en.put(Integer.valueOf("500"), "Montserrat");
		countryCodelist_en.put(Integer.valueOf("508"), "Mozambique");
		countryCodelist_en.put(Integer.valueOf("104"), "Myanmar");
		countryCodelist_en.put(Integer.valueOf("516"), "Namibia");
		countryCodelist_en.put(Integer.valueOf("520"), "Nauru");
		countryCodelist_en.put(Integer.valueOf("524"), "Nepal");
		countryCodelist_en.put(Integer.valueOf("540"), "New Caledonia");
		countryCodelist_en.put(Integer.valueOf("554"), "New Zealand");
		countryCodelist_en.put(Integer.valueOf("558"), "Nicaragua");
		countryCodelist_en.put(Integer.valueOf("528"), "Netherlands");
		countryCodelist_en.put(Integer.valueOf("530"), "Netherlands Antilles");
		countryCodelist_en.put(Integer.valueOf("562"), "Niger");
		countryCodelist_en.put(Integer.valueOf("566"), "Nigeria");
		countryCodelist_en.put(Integer.valueOf("570"), "Niue");
		countryCodelist_en.put(Integer.valueOf("580"), "Northern Mariana Islands");
		countryCodelist_en.put(Integer.valueOf("574"), "Norfolk Island");
		countryCodelist_en.put(Integer.valueOf("578"), "Norway");
		countryCodelist_en.put(Integer.valueOf("512"), "Oman");
		countryCodelist_en.put(Integer.valueOf("40"), "Austria");
		countryCodelist_en.put(Integer.valueOf("626"), "Timor-Leste");
		countryCodelist_en.put(Integer.valueOf("586"), "Pakistan");
		countryCodelist_en.put(Integer.valueOf("275"), "Palestinian Territory, Occupied");
		countryCodelist_en.put(Integer.valueOf("585"), "Palau");
		countryCodelist_en.put(Integer.valueOf("591"), "Panama");
		countryCodelist_en.put(Integer.valueOf("598"), "Papua New Guinea");
		countryCodelist_en.put(Integer.valueOf("600"), "Paraguay");
		countryCodelist_en.put(Integer.valueOf("604"), "Peru");
		countryCodelist_en.put(Integer.valueOf("608"), "Philippines");
		countryCodelist_en.put(Integer.valueOf("612"), "Pitcairn");
		countryCodelist_en.put(Integer.valueOf("616"), "Poland");
		countryCodelist_en.put(Integer.valueOf("620"), "Portugal");
		countryCodelist_en.put(Integer.valueOf("630"), "Puerto Rico");
		countryCodelist_en.put(Integer.valueOf("158"), "Taiwan, Province of China");
		countryCodelist_en.put(Integer.valueOf("178"), "Congo");
		countryCodelist_en.put(Integer.valueOf("638"), "R\u00e9union");
		countryCodelist_en.put(Integer.valueOf("646"), "Rwanda");
		countryCodelist_en.put(Integer.valueOf("642"), "Romania");
		countryCodelist_en.put(Integer.valueOf("643"), "Russian Federation");
		countryCodelist_en.put(Integer.valueOf("652"), "Saint Barth\u00e9lemy");
		countryCodelist_en.put(Integer.valueOf("663"), "Saint Martin (French part)");
		countryCodelist_en.put(Integer.valueOf("90"), "Solomon Islands");
		countryCodelist_en.put(Integer.valueOf("894"), "Zambia");
		countryCodelist_en.put(Integer.valueOf("882"), "Samoa");
		countryCodelist_en.put(Integer.valueOf("674"), "San Marino");
		countryCodelist_en.put(Integer.valueOf("678"), "Sao Tome and Principe");
		countryCodelist_en.put(Integer.valueOf("682"), "Saudi Arabia");
		countryCodelist_en.put(Integer.valueOf("752"), "Sweden");
		countryCodelist_en.put(Integer.valueOf("756"), "Switzerland");
		countryCodelist_en.put(Integer.valueOf("686"), "Senegal");
		countryCodelist_en.put(Integer.valueOf("688"), "Serbia");
		countryCodelist_en.put(Integer.valueOf("690"), "Seychelles");
		countryCodelist_en.put(Integer.valueOf("694"), "Sierra Leone");
		countryCodelist_en.put(Integer.valueOf("716"), "Zimbabwe");
		countryCodelist_en.put(Integer.valueOf("702"), "Singapore");
		countryCodelist_en.put(Integer.valueOf("703"), "Slovakia");
		countryCodelist_en.put(Integer.valueOf("705"), "Slovenia");
		countryCodelist_en.put(Integer.valueOf("706"), "Somalia");
		countryCodelist_en.put(Integer.valueOf("724"), "Spain");
		countryCodelist_en.put(Integer.valueOf("144"), "Sri Lanka");
		countryCodelist_en.put(Integer.valueOf("654"), "Saint Helena");
		countryCodelist_en.put(Integer.valueOf("659"), "Saint Kitts and Nevis");
		countryCodelist_en.put(Integer.valueOf("662"), "Saint Lucia");
		countryCodelist_en.put(Integer.valueOf("666"), "Saint Pierre and Miquelon");
		countryCodelist_en.put(Integer.valueOf("670"), "Saint Vincent and the Grenadines");
		countryCodelist_en.put(Integer.valueOf("710"), "South Africa");
		countryCodelist_en.put(Integer.valueOf("736"), "Sudan");
		countryCodelist_en.put(Integer.valueOf("239"), "South Georgia and the South Sandwich Islands");
		countryCodelist_en.put(Integer.valueOf("740"), "Suriname");
		countryCodelist_en.put(Integer.valueOf("744"), "Svalbard and Jan Mayen");
		countryCodelist_en.put(Integer.valueOf("748"), "Swaziland");
		countryCodelist_en.put(Integer.valueOf("760"), "Syrian Arab Republic");
		countryCodelist_en.put(Integer.valueOf("762"), "Tajikistan");
		countryCodelist_en.put(Integer.valueOf("834"), "Tanzania, United Republic of");
		countryCodelist_en.put(Integer.valueOf("764"), "Thailand");
		countryCodelist_en.put(Integer.valueOf("768"), "Togo");
		countryCodelist_en.put(Integer.valueOf("772"), "Tokelau");
		countryCodelist_en.put(Integer.valueOf("776"), "Tonga");
		countryCodelist_en.put(Integer.valueOf("780"), "Trinidad and Tobago");
		countryCodelist_en.put(Integer.valueOf("148"), "Chad");
		countryCodelist_en.put(Integer.valueOf("203"), "Czech Republic");
		countryCodelist_en.put(Integer.valueOf("788"), "Tunisia");
		countryCodelist_en.put(Integer.valueOf("792"), "Turkey");
		countryCodelist_en.put(Integer.valueOf("795"), "Turkmenistan");
		countryCodelist_en.put(Integer.valueOf("796"), "Turks and Caicos Islands");
		countryCodelist_en.put(Integer.valueOf("798"), "Tuvalu");
		countryCodelist_en.put(Integer.valueOf("800"), "Uganda");
		countryCodelist_en.put(Integer.valueOf("804"), "Ukraine");
		countryCodelist_en.put(Integer.valueOf("348"), "Hungary");
		countryCodelist_en.put(Integer.valueOf("581"), "United States Minor Outlying Islands");
		countryCodelist_en.put(Integer.valueOf("858"), "Uruguay");
		countryCodelist_en.put(Integer.valueOf("860"), "Uzbekistan");
		countryCodelist_en.put(Integer.valueOf("548"), "Vanuatu");
		countryCodelist_en.put(Integer.valueOf("336"), "Holy See (Vatican City State)");
		countryCodelist_en.put(Integer.valueOf("862"), "Venezuela, Bolivarian Republic of");
		countryCodelist_en.put(Integer.valueOf("784"), "United Arab Emirates");
		countryCodelist_en.put(Integer.valueOf("840"), "United States");
		countryCodelist_en.put(Integer.valueOf("826"), "United Kingdom");
		countryCodelist_en.put(Integer.valueOf("704"), "Viet Nam");
		countryCodelist_en.put(Integer.valueOf("876"), "Wallis and Futuna");
		countryCodelist_en.put(Integer.valueOf("162"), "Christmas Island");
		countryCodelist_en.put(Integer.valueOf("732"), "Western Sahara");
		countryCodelist_en.put(Integer.valueOf("140"), "Central African Republic");
		countryCodelist_en.put(Integer.valueOf("196"), "Cyprus");
	}

	/** MAP: 2 letter ISO country shortcut ("DE", "GB") to ISO country code <2 letter ISO country shortcut, ISO country code>*/
	static private HashMap<String, Integer> countryShortcut2ToCode = new HashMap<String, Integer>(); 
	static {
		countryShortcut2ToCode.put("AF", Integer.valueOf(4));
		countryShortcut2ToCode.put("EG", Integer.valueOf(818));
		countryShortcut2ToCode.put("AX", Integer.valueOf(248));
		countryShortcut2ToCode.put("AL", Integer.valueOf(8));
		countryShortcut2ToCode.put("DZ", Integer.valueOf(12));
		countryShortcut2ToCode.put("VI", Integer.valueOf(850));
		countryShortcut2ToCode.put("AS", Integer.valueOf(16));
		countryShortcut2ToCode.put("AD", Integer.valueOf(20));
		countryShortcut2ToCode.put("AO", Integer.valueOf(24));
		countryShortcut2ToCode.put("AI", Integer.valueOf(660));
		countryShortcut2ToCode.put("AQ", Integer.valueOf(10));
		countryShortcut2ToCode.put("AG", Integer.valueOf(28));
		countryShortcut2ToCode.put("GQ", Integer.valueOf(226));
		countryShortcut2ToCode.put("AR", Integer.valueOf(32));
		countryShortcut2ToCode.put("AM", Integer.valueOf(51));
		countryShortcut2ToCode.put("AW", Integer.valueOf(533));
		countryShortcut2ToCode.put("AZ", Integer.valueOf(31));
		countryShortcut2ToCode.put("ET", Integer.valueOf(231));
		countryShortcut2ToCode.put("AU", Integer.valueOf(36));
		countryShortcut2ToCode.put("BS", Integer.valueOf(44));
		countryShortcut2ToCode.put("BH", Integer.valueOf(48));
		countryShortcut2ToCode.put("BD", Integer.valueOf(50));
		countryShortcut2ToCode.put("BB", Integer.valueOf(52));
		countryShortcut2ToCode.put("BY", Integer.valueOf(112));
		countryShortcut2ToCode.put("BE", Integer.valueOf(56));
		countryShortcut2ToCode.put("BZ", Integer.valueOf(84));
		countryShortcut2ToCode.put("BJ", Integer.valueOf(204));
		countryShortcut2ToCode.put("BM", Integer.valueOf(60));
		countryShortcut2ToCode.put("BT", Integer.valueOf(64));
		countryShortcut2ToCode.put("BO", Integer.valueOf(68));
		countryShortcut2ToCode.put("BA", Integer.valueOf(70));
		countryShortcut2ToCode.put("BW", Integer.valueOf(72));
		countryShortcut2ToCode.put("BV", Integer.valueOf(74));
		countryShortcut2ToCode.put("BR", Integer.valueOf(76));
		countryShortcut2ToCode.put("VG", Integer.valueOf(92));
		countryShortcut2ToCode.put("IO", Integer.valueOf(86));
		countryShortcut2ToCode.put("BN", Integer.valueOf(96));
		countryShortcut2ToCode.put("BG", Integer.valueOf(100));
		countryShortcut2ToCode.put("BF", Integer.valueOf(854));
		countryShortcut2ToCode.put("BI", Integer.valueOf(108));
		countryShortcut2ToCode.put("CL", Integer.valueOf(152));
		countryShortcut2ToCode.put("CN", Integer.valueOf(156));
		countryShortcut2ToCode.put("CK", Integer.valueOf(184));
		countryShortcut2ToCode.put("CR", Integer.valueOf(188));
		countryShortcut2ToCode.put("CI", Integer.valueOf(384));
		countryShortcut2ToCode.put("DK", Integer.valueOf(208));
		countryShortcut2ToCode.put("DE", Integer.valueOf(276));
		countryShortcut2ToCode.put("DM", Integer.valueOf(212));
		countryShortcut2ToCode.put("DO", Integer.valueOf(214));
		countryShortcut2ToCode.put("DJ", Integer.valueOf(262));
		countryShortcut2ToCode.put("EC", Integer.valueOf(218));
		countryShortcut2ToCode.put("SV", Integer.valueOf(222));
		countryShortcut2ToCode.put("ER", Integer.valueOf(232));
		countryShortcut2ToCode.put("EE", Integer.valueOf(233));
		countryShortcut2ToCode.put("FK", Integer.valueOf(238));
		countryShortcut2ToCode.put("FO", Integer.valueOf(234));
		countryShortcut2ToCode.put("FJ", Integer.valueOf(242));
		countryShortcut2ToCode.put("FI", Integer.valueOf(246));
		countryShortcut2ToCode.put("FR", Integer.valueOf(250));
		countryShortcut2ToCode.put("TF", Integer.valueOf(260));
		countryShortcut2ToCode.put("GF", Integer.valueOf(254));
		countryShortcut2ToCode.put("PF", Integer.valueOf(258));
		countryShortcut2ToCode.put("GA", Integer.valueOf(266));
		countryShortcut2ToCode.put("GM", Integer.valueOf(270));
		countryShortcut2ToCode.put("GE", Integer.valueOf(268));
		countryShortcut2ToCode.put("GH", Integer.valueOf(288));
		countryShortcut2ToCode.put("GI", Integer.valueOf(292));
		countryShortcut2ToCode.put("GD", Integer.valueOf(308));
		countryShortcut2ToCode.put("GR", Integer.valueOf(300));
		countryShortcut2ToCode.put("GL", Integer.valueOf(304));
		countryShortcut2ToCode.put("GP", Integer.valueOf(312));
		countryShortcut2ToCode.put("GU", Integer.valueOf(316));
		countryShortcut2ToCode.put("GT", Integer.valueOf(320));
		countryShortcut2ToCode.put("GG", Integer.valueOf(831));
		countryShortcut2ToCode.put("GN", Integer.valueOf(324));
		countryShortcut2ToCode.put("GW", Integer.valueOf(624));
		countryShortcut2ToCode.put("GY", Integer.valueOf(328));
		countryShortcut2ToCode.put("HT", Integer.valueOf(332));
		countryShortcut2ToCode.put("HM", Integer.valueOf(334));
		countryShortcut2ToCode.put("HN", Integer.valueOf(340));
		countryShortcut2ToCode.put("HK", Integer.valueOf(344));
		countryShortcut2ToCode.put("IN", Integer.valueOf(356));
		countryShortcut2ToCode.put("ID", Integer.valueOf(360));
		countryShortcut2ToCode.put("IM", Integer.valueOf(833));
		countryShortcut2ToCode.put("IQ", Integer.valueOf(368));
		countryShortcut2ToCode.put("IR", Integer.valueOf(364));
		countryShortcut2ToCode.put("IE", Integer.valueOf(372));
		countryShortcut2ToCode.put("IS", Integer.valueOf(352));
		countryShortcut2ToCode.put("IL", Integer.valueOf(376));
		countryShortcut2ToCode.put("IT", Integer.valueOf(380));
		countryShortcut2ToCode.put("JM", Integer.valueOf(388));
		countryShortcut2ToCode.put("JP", Integer.valueOf(392));
		countryShortcut2ToCode.put("YE", Integer.valueOf(887));
		countryShortcut2ToCode.put("JE", Integer.valueOf(832));
		countryShortcut2ToCode.put("JO", Integer.valueOf(400));
		countryShortcut2ToCode.put("KY", Integer.valueOf(136));
		countryShortcut2ToCode.put("KH", Integer.valueOf(116));
		countryShortcut2ToCode.put("CM", Integer.valueOf(120));
		countryShortcut2ToCode.put("CA", Integer.valueOf(124));
		countryShortcut2ToCode.put("CV", Integer.valueOf(132));
		countryShortcut2ToCode.put("KZ", Integer.valueOf(398));
		countryShortcut2ToCode.put("QA", Integer.valueOf(634));
		countryShortcut2ToCode.put("KE", Integer.valueOf(404));
		countryShortcut2ToCode.put("KG", Integer.valueOf(417));
		countryShortcut2ToCode.put("KI", Integer.valueOf(296));
		countryShortcut2ToCode.put("CC", Integer.valueOf(166));
		countryShortcut2ToCode.put("CO", Integer.valueOf(170));
		countryShortcut2ToCode.put("KM", Integer.valueOf(174));
		countryShortcut2ToCode.put("CD", Integer.valueOf(180));
		countryShortcut2ToCode.put("KP", Integer.valueOf(408));
		countryShortcut2ToCode.put("KR", Integer.valueOf(410));
		countryShortcut2ToCode.put("HR", Integer.valueOf(191));
		countryShortcut2ToCode.put("CU", Integer.valueOf(192));
		countryShortcut2ToCode.put("KW", Integer.valueOf(414));
		countryShortcut2ToCode.put("LA", Integer.valueOf(418));
		countryShortcut2ToCode.put("LS", Integer.valueOf(426));
		countryShortcut2ToCode.put("LV", Integer.valueOf(428));
		countryShortcut2ToCode.put("LB", Integer.valueOf(422));
		countryShortcut2ToCode.put("LR", Integer.valueOf(430));
		countryShortcut2ToCode.put("LY", Integer.valueOf(434));
		countryShortcut2ToCode.put("LI", Integer.valueOf(438));
		countryShortcut2ToCode.put("LT", Integer.valueOf(440));
		countryShortcut2ToCode.put("LU", Integer.valueOf(442));
		countryShortcut2ToCode.put("MO", Integer.valueOf(446));
		countryShortcut2ToCode.put("MG", Integer.valueOf(450));
		countryShortcut2ToCode.put("MW", Integer.valueOf(454));
		countryShortcut2ToCode.put("MY", Integer.valueOf(458));
		countryShortcut2ToCode.put("MV", Integer.valueOf(462));
		countryShortcut2ToCode.put("ML", Integer.valueOf(466));
		countryShortcut2ToCode.put("MT", Integer.valueOf(470));
		countryShortcut2ToCode.put("MA", Integer.valueOf(504));
		countryShortcut2ToCode.put("MH", Integer.valueOf(584));
		countryShortcut2ToCode.put("MQ", Integer.valueOf(474));
		countryShortcut2ToCode.put("MR", Integer.valueOf(478));
		countryShortcut2ToCode.put("MU", Integer.valueOf(480));
		countryShortcut2ToCode.put("YT", Integer.valueOf(175));
		countryShortcut2ToCode.put("MK", Integer.valueOf(807));
		countryShortcut2ToCode.put("MX", Integer.valueOf(484));
		countryShortcut2ToCode.put("FM", Integer.valueOf(583));
		countryShortcut2ToCode.put("MD", Integer.valueOf(498));
		countryShortcut2ToCode.put("MC", Integer.valueOf(492));
		countryShortcut2ToCode.put("MN", Integer.valueOf(496));
		countryShortcut2ToCode.put("ME", Integer.valueOf(499));
		countryShortcut2ToCode.put("MS", Integer.valueOf(500));
		countryShortcut2ToCode.put("MZ", Integer.valueOf(508));
		countryShortcut2ToCode.put("MM", Integer.valueOf(104));
		countryShortcut2ToCode.put("NA", Integer.valueOf(516));
		countryShortcut2ToCode.put("NR", Integer.valueOf(520));
		countryShortcut2ToCode.put("NP", Integer.valueOf(524));
		countryShortcut2ToCode.put("NC", Integer.valueOf(540));
		countryShortcut2ToCode.put("NZ", Integer.valueOf(554));
		countryShortcut2ToCode.put("NI", Integer.valueOf(558));
		countryShortcut2ToCode.put("NL", Integer.valueOf(528));
		countryShortcut2ToCode.put("AN", Integer.valueOf(530));
		countryShortcut2ToCode.put("NE", Integer.valueOf(562));
		countryShortcut2ToCode.put("NG", Integer.valueOf(566));
		countryShortcut2ToCode.put("NU", Integer.valueOf(570));
		countryShortcut2ToCode.put("MP", Integer.valueOf(580));
		countryShortcut2ToCode.put("NF", Integer.valueOf(574));
		countryShortcut2ToCode.put("NO", Integer.valueOf(578));
		countryShortcut2ToCode.put("OM", Integer.valueOf(512));
		countryShortcut2ToCode.put("AT", Integer.valueOf(40));
		countryShortcut2ToCode.put("TL", Integer.valueOf(626));
		countryShortcut2ToCode.put("PK", Integer.valueOf(586));
		countryShortcut2ToCode.put("PS", Integer.valueOf(275));
		countryShortcut2ToCode.put("PW", Integer.valueOf(585));
		countryShortcut2ToCode.put("PA", Integer.valueOf(591));
		countryShortcut2ToCode.put("PG", Integer.valueOf(598));
		countryShortcut2ToCode.put("PY", Integer.valueOf(600));
		countryShortcut2ToCode.put("PE", Integer.valueOf(604));
		countryShortcut2ToCode.put("PH", Integer.valueOf(608));
		countryShortcut2ToCode.put("PN", Integer.valueOf(612));
		countryShortcut2ToCode.put("PL", Integer.valueOf(616));
		countryShortcut2ToCode.put("PT", Integer.valueOf(620));
		countryShortcut2ToCode.put("PR", Integer.valueOf(630));
		countryShortcut2ToCode.put("TW", Integer.valueOf(158));
		countryShortcut2ToCode.put("CG", Integer.valueOf(178));
		countryShortcut2ToCode.put("RE", Integer.valueOf(638));
		countryShortcut2ToCode.put("RW", Integer.valueOf(646));
		countryShortcut2ToCode.put("RO", Integer.valueOf(642));
		countryShortcut2ToCode.put("RU", Integer.valueOf(643));
		countryShortcut2ToCode.put("BL", Integer.valueOf(652));
		countryShortcut2ToCode.put("MF", Integer.valueOf(663));
		countryShortcut2ToCode.put("SB", Integer.valueOf(90));
		countryShortcut2ToCode.put("ZM", Integer.valueOf(894));
		countryShortcut2ToCode.put("WS", Integer.valueOf(882));
		countryShortcut2ToCode.put("SM", Integer.valueOf(674));
		countryShortcut2ToCode.put("ST", Integer.valueOf(678));
		countryShortcut2ToCode.put("SA", Integer.valueOf(682));
		countryShortcut2ToCode.put("SE", Integer.valueOf(752));
		countryShortcut2ToCode.put("CH", Integer.valueOf(756));
		countryShortcut2ToCode.put("SN", Integer.valueOf(686));
		countryShortcut2ToCode.put("RS", Integer.valueOf(688));
		countryShortcut2ToCode.put("SC", Integer.valueOf(690));
		countryShortcut2ToCode.put("SL", Integer.valueOf(694));
		countryShortcut2ToCode.put("ZW", Integer.valueOf(716));
		countryShortcut2ToCode.put("SG", Integer.valueOf(702));
		countryShortcut2ToCode.put("SK", Integer.valueOf(703));
		countryShortcut2ToCode.put("SI", Integer.valueOf(705));
		countryShortcut2ToCode.put("SO", Integer.valueOf(706));
		countryShortcut2ToCode.put("ES", Integer.valueOf(724));
		countryShortcut2ToCode.put("LK", Integer.valueOf(144));
		countryShortcut2ToCode.put("SH", Integer.valueOf(654));
		countryShortcut2ToCode.put("KN", Integer.valueOf(659));
		countryShortcut2ToCode.put("LC", Integer.valueOf(662));
		countryShortcut2ToCode.put("PM", Integer.valueOf(666));
		countryShortcut2ToCode.put("VC", Integer.valueOf(670));
		countryShortcut2ToCode.put("ZA", Integer.valueOf(710));
		countryShortcut2ToCode.put("SD", Integer.valueOf(736));
		countryShortcut2ToCode.put("GS", Integer.valueOf(239));
		countryShortcut2ToCode.put("SR", Integer.valueOf(740));
		countryShortcut2ToCode.put("SJ", Integer.valueOf(744));
		countryShortcut2ToCode.put("SZ", Integer.valueOf(748));
		countryShortcut2ToCode.put("SY", Integer.valueOf(760));
		countryShortcut2ToCode.put("TJ", Integer.valueOf(762));
		countryShortcut2ToCode.put("TZ", Integer.valueOf(834));
		countryShortcut2ToCode.put("TH", Integer.valueOf(764));
		countryShortcut2ToCode.put("TG", Integer.valueOf(768));
		countryShortcut2ToCode.put("TK", Integer.valueOf(772));
		countryShortcut2ToCode.put("TO", Integer.valueOf(776));
		countryShortcut2ToCode.put("TT", Integer.valueOf(780));
		countryShortcut2ToCode.put("TD", Integer.valueOf(148));
		countryShortcut2ToCode.put("CZ", Integer.valueOf(203));
		countryShortcut2ToCode.put("TN", Integer.valueOf(788));
		countryShortcut2ToCode.put("TR", Integer.valueOf(792));
		countryShortcut2ToCode.put("TM", Integer.valueOf(795));
		countryShortcut2ToCode.put("TC", Integer.valueOf(796));
		countryShortcut2ToCode.put("TV", Integer.valueOf(798));
		countryShortcut2ToCode.put("UG", Integer.valueOf(800));
		countryShortcut2ToCode.put("UA", Integer.valueOf(804));
		countryShortcut2ToCode.put("HU", Integer.valueOf(348));
		countryShortcut2ToCode.put("UM", Integer.valueOf(581));
		countryShortcut2ToCode.put("UY", Integer.valueOf(858));
		countryShortcut2ToCode.put("UZ", Integer.valueOf(860));
		countryShortcut2ToCode.put("VU", Integer.valueOf(548));
		countryShortcut2ToCode.put("VA", Integer.valueOf(336));
		countryShortcut2ToCode.put("VE", Integer.valueOf(862));
		countryShortcut2ToCode.put("AE", Integer.valueOf(784));
		countryShortcut2ToCode.put("US", Integer.valueOf(840));
		countryShortcut2ToCode.put("GB", Integer.valueOf(826));
		countryShortcut2ToCode.put("VN", Integer.valueOf(704));
		countryShortcut2ToCode.put("WF", Integer.valueOf(876));
		countryShortcut2ToCode.put("CX", Integer.valueOf(162));
		countryShortcut2ToCode.put("EH", Integer.valueOf(732));
		countryShortcut2ToCode.put("CF", Integer.valueOf(140));
		countryShortcut2ToCode.put("CY", Integer.valueOf(196));
	}

	/** MAP: 3 letter ISO country shortcut ("DEU", "GBR") to ISO country code <3 letter ISO country shortcut, ISO country code>*/
	static private HashMap<String, Integer> countryShortcut3ToCode = new HashMap<String, Integer>(); 
	static {
		countryShortcut3ToCode.put("AFG", Integer.valueOf(4));
		countryShortcut3ToCode.put("EGY", Integer.valueOf(818));
		countryShortcut3ToCode.put("ALA", Integer.valueOf(248));
		countryShortcut3ToCode.put("ALB", Integer.valueOf(8));
		countryShortcut3ToCode.put("DZA", Integer.valueOf(12));
		countryShortcut3ToCode.put("VIR", Integer.valueOf(850));
		countryShortcut3ToCode.put("ASM", Integer.valueOf(16));
		countryShortcut3ToCode.put("AND", Integer.valueOf(20));
		countryShortcut3ToCode.put("AGO", Integer.valueOf(24));
		countryShortcut3ToCode.put("AIA", Integer.valueOf(660));
		countryShortcut3ToCode.put("ATA", Integer.valueOf(10));
		countryShortcut3ToCode.put("ATG", Integer.valueOf(28));
		countryShortcut3ToCode.put("GNQ", Integer.valueOf(226));
		countryShortcut3ToCode.put("ARG", Integer.valueOf(32));
		countryShortcut3ToCode.put("ARM", Integer.valueOf(51));
		countryShortcut3ToCode.put("ABW", Integer.valueOf(533));
		countryShortcut3ToCode.put("AZE", Integer.valueOf(31));
		countryShortcut3ToCode.put("ETH", Integer.valueOf(231));
		countryShortcut3ToCode.put("AUS", Integer.valueOf(36));
		countryShortcut3ToCode.put("BHS", Integer.valueOf(44));
		countryShortcut3ToCode.put("BHR", Integer.valueOf(48));
		countryShortcut3ToCode.put("BGD", Integer.valueOf(50));
		countryShortcut3ToCode.put("BRB", Integer.valueOf(52));
		countryShortcut3ToCode.put("BLR", Integer.valueOf(112));
		countryShortcut3ToCode.put("BEL", Integer.valueOf(56));
		countryShortcut3ToCode.put("BLZ", Integer.valueOf(84));
		countryShortcut3ToCode.put("BEN", Integer.valueOf(204));
		countryShortcut3ToCode.put("BMU", Integer.valueOf(60));
		countryShortcut3ToCode.put("BTN", Integer.valueOf(64));
		countryShortcut3ToCode.put("BOL", Integer.valueOf(68));
		countryShortcut3ToCode.put("BIH", Integer.valueOf(70));
		countryShortcut3ToCode.put("BWA", Integer.valueOf(72));
		countryShortcut3ToCode.put("BVT", Integer.valueOf(74));
		countryShortcut3ToCode.put("BRA", Integer.valueOf(76));
		countryShortcut3ToCode.put("VGB", Integer.valueOf(92));
		countryShortcut3ToCode.put("IOT", Integer.valueOf(86));
		countryShortcut3ToCode.put("BRN", Integer.valueOf(96));
		countryShortcut3ToCode.put("BGR", Integer.valueOf(100));
		countryShortcut3ToCode.put("BFA", Integer.valueOf(854));
		countryShortcut3ToCode.put("BDI", Integer.valueOf(108));
		countryShortcut3ToCode.put("CHL", Integer.valueOf(152));
		countryShortcut3ToCode.put("CHN", Integer.valueOf(156));
		countryShortcut3ToCode.put("COK", Integer.valueOf(184));
		countryShortcut3ToCode.put("CRI", Integer.valueOf(188));
		countryShortcut3ToCode.put("CIV", Integer.valueOf(384));
		countryShortcut3ToCode.put("DNK", Integer.valueOf(208));
		countryShortcut3ToCode.put("DEU", Integer.valueOf(276));
		countryShortcut3ToCode.put("DMA", Integer.valueOf(212));
		countryShortcut3ToCode.put("DOM", Integer.valueOf(214));
		countryShortcut3ToCode.put("DJI", Integer.valueOf(262));
		countryShortcut3ToCode.put("ECU", Integer.valueOf(218));
		countryShortcut3ToCode.put("SLV", Integer.valueOf(222));
		countryShortcut3ToCode.put("ERI", Integer.valueOf(232));
		countryShortcut3ToCode.put("EST", Integer.valueOf(233));
		countryShortcut3ToCode.put("FLK", Integer.valueOf(238));
		countryShortcut3ToCode.put("FRO", Integer.valueOf(234));
		countryShortcut3ToCode.put("FJI", Integer.valueOf(242));
		countryShortcut3ToCode.put("FIN", Integer.valueOf(246));
		countryShortcut3ToCode.put("FRA", Integer.valueOf(250));
		countryShortcut3ToCode.put("ATF", Integer.valueOf(260));
		countryShortcut3ToCode.put("GUF", Integer.valueOf(254));
		countryShortcut3ToCode.put("PYF", Integer.valueOf(258));
		countryShortcut3ToCode.put("GAB", Integer.valueOf(266));
		countryShortcut3ToCode.put("GMB", Integer.valueOf(270));
		countryShortcut3ToCode.put("GEO", Integer.valueOf(268));
		countryShortcut3ToCode.put("GHA", Integer.valueOf(288));
		countryShortcut3ToCode.put("GIB", Integer.valueOf(292));
		countryShortcut3ToCode.put("GRD", Integer.valueOf(308));
		countryShortcut3ToCode.put("GRC", Integer.valueOf(300));
		countryShortcut3ToCode.put("GRL", Integer.valueOf(304));
		countryShortcut3ToCode.put("GLP", Integer.valueOf(312));
		countryShortcut3ToCode.put("GUM", Integer.valueOf(316));
		countryShortcut3ToCode.put("GTM", Integer.valueOf(320));
		countryShortcut3ToCode.put("GGY", Integer.valueOf(831));
		countryShortcut3ToCode.put("GIN", Integer.valueOf(324));
		countryShortcut3ToCode.put("GNB", Integer.valueOf(624));
		countryShortcut3ToCode.put("GUY", Integer.valueOf(328));
		countryShortcut3ToCode.put("HTI", Integer.valueOf(332));
		countryShortcut3ToCode.put("HMD", Integer.valueOf(334));
		countryShortcut3ToCode.put("HND", Integer.valueOf(340));
		countryShortcut3ToCode.put("HKG", Integer.valueOf(344));
		countryShortcut3ToCode.put("IND", Integer.valueOf(356));
		countryShortcut3ToCode.put("IDN", Integer.valueOf(360));
		countryShortcut3ToCode.put("IMN", Integer.valueOf(833));
		countryShortcut3ToCode.put("IRQ", Integer.valueOf(368));
		countryShortcut3ToCode.put("IRN", Integer.valueOf(364));
		countryShortcut3ToCode.put("IRL", Integer.valueOf(372));
		countryShortcut3ToCode.put("ISL", Integer.valueOf(352));
		countryShortcut3ToCode.put("ISR", Integer.valueOf(376));
		countryShortcut3ToCode.put("ITA", Integer.valueOf(380));
		countryShortcut3ToCode.put("JAM", Integer.valueOf(388));
		countryShortcut3ToCode.put("JPN", Integer.valueOf(392));
		countryShortcut3ToCode.put("YEM", Integer.valueOf(887));
		countryShortcut3ToCode.put("JEY", Integer.valueOf(832));
		countryShortcut3ToCode.put("JOR", Integer.valueOf(400));
		countryShortcut3ToCode.put("CYM", Integer.valueOf(136));
		countryShortcut3ToCode.put("KHM", Integer.valueOf(116));
		countryShortcut3ToCode.put("CMR", Integer.valueOf(120));
		countryShortcut3ToCode.put("CAN", Integer.valueOf(124));
		countryShortcut3ToCode.put("CPV", Integer.valueOf(132));
		countryShortcut3ToCode.put("KAZ", Integer.valueOf(398));
		countryShortcut3ToCode.put("QAT", Integer.valueOf(634));
		countryShortcut3ToCode.put("KEN", Integer.valueOf(404));
		countryShortcut3ToCode.put("KGZ", Integer.valueOf(417));
		countryShortcut3ToCode.put("KIR", Integer.valueOf(296));
		countryShortcut3ToCode.put("CCK", Integer.valueOf(166));
		countryShortcut3ToCode.put("COL", Integer.valueOf(170));
		countryShortcut3ToCode.put("COM", Integer.valueOf(174));
		countryShortcut3ToCode.put("COD", Integer.valueOf(180));
		countryShortcut3ToCode.put("PRK", Integer.valueOf(408));
		countryShortcut3ToCode.put("KOR", Integer.valueOf(410));
		countryShortcut3ToCode.put("HRV", Integer.valueOf(191));
		countryShortcut3ToCode.put("CUB", Integer.valueOf(192));
		countryShortcut3ToCode.put("KWT", Integer.valueOf(414));
		countryShortcut3ToCode.put("LAO", Integer.valueOf(418));
		countryShortcut3ToCode.put("LSO", Integer.valueOf(426));
		countryShortcut3ToCode.put("LVA", Integer.valueOf(428));
		countryShortcut3ToCode.put("LBN", Integer.valueOf(422));
		countryShortcut3ToCode.put("LBR", Integer.valueOf(430));
		countryShortcut3ToCode.put("LBY", Integer.valueOf(434));
		countryShortcut3ToCode.put("LIE", Integer.valueOf(438));
		countryShortcut3ToCode.put("LTU", Integer.valueOf(440));
		countryShortcut3ToCode.put("LUX", Integer.valueOf(442));
		countryShortcut3ToCode.put("MAC", Integer.valueOf(446));
		countryShortcut3ToCode.put("MDG", Integer.valueOf(450));
		countryShortcut3ToCode.put("MWI", Integer.valueOf(454));
		countryShortcut3ToCode.put("MYS", Integer.valueOf(458));
		countryShortcut3ToCode.put("MDV", Integer.valueOf(462));
		countryShortcut3ToCode.put("MLI", Integer.valueOf(466));
		countryShortcut3ToCode.put("MLT", Integer.valueOf(470));
		countryShortcut3ToCode.put("MAR", Integer.valueOf(504));
		countryShortcut3ToCode.put("MHL", Integer.valueOf(584));
		countryShortcut3ToCode.put("MTQ", Integer.valueOf(474));
		countryShortcut3ToCode.put("MRT", Integer.valueOf(478));
		countryShortcut3ToCode.put("MUS", Integer.valueOf(480));
		countryShortcut3ToCode.put("MYT", Integer.valueOf(175));
		countryShortcut3ToCode.put("MKD", Integer.valueOf(807));
		countryShortcut3ToCode.put("MEX", Integer.valueOf(484));
		countryShortcut3ToCode.put("FSM", Integer.valueOf(583));
		countryShortcut3ToCode.put("MDA", Integer.valueOf(498));
		countryShortcut3ToCode.put("MCO", Integer.valueOf(492));
		countryShortcut3ToCode.put("MNG", Integer.valueOf(496));
		countryShortcut3ToCode.put("MNE", Integer.valueOf(499));
		countryShortcut3ToCode.put("MSR", Integer.valueOf(500));
		countryShortcut3ToCode.put("MOZ", Integer.valueOf(508));
		countryShortcut3ToCode.put("MMR", Integer.valueOf(104));
		countryShortcut3ToCode.put("NAM", Integer.valueOf(516));
		countryShortcut3ToCode.put("NRU", Integer.valueOf(520));
		countryShortcut3ToCode.put("NPL", Integer.valueOf(524));
		countryShortcut3ToCode.put("NCL", Integer.valueOf(540));
		countryShortcut3ToCode.put("NZL", Integer.valueOf(554));
		countryShortcut3ToCode.put("NIC", Integer.valueOf(558));
		countryShortcut3ToCode.put("NLD", Integer.valueOf(528));
		countryShortcut3ToCode.put("ANT", Integer.valueOf(530));
		countryShortcut3ToCode.put("NER", Integer.valueOf(562));
		countryShortcut3ToCode.put("NGA", Integer.valueOf(566));
		countryShortcut3ToCode.put("NIU", Integer.valueOf(570));
		countryShortcut3ToCode.put("MNP", Integer.valueOf(580));
		countryShortcut3ToCode.put("NFK", Integer.valueOf(574));
		countryShortcut3ToCode.put("NOR", Integer.valueOf(578));
		countryShortcut3ToCode.put("OMN", Integer.valueOf(512));
		countryShortcut3ToCode.put("AUT", Integer.valueOf(40));
		countryShortcut3ToCode.put("TLS", Integer.valueOf(626));
		countryShortcut3ToCode.put("PAK", Integer.valueOf(586));
		countryShortcut3ToCode.put("PSE", Integer.valueOf(275));
		countryShortcut3ToCode.put("PLW", Integer.valueOf(585));
		countryShortcut3ToCode.put("PAN", Integer.valueOf(591));
		countryShortcut3ToCode.put("PNG", Integer.valueOf(598));
		countryShortcut3ToCode.put("PRY", Integer.valueOf(600));
		countryShortcut3ToCode.put("PER", Integer.valueOf(604));
		countryShortcut3ToCode.put("PHL", Integer.valueOf(608));
		countryShortcut3ToCode.put("PCN", Integer.valueOf(612));
		countryShortcut3ToCode.put("POL", Integer.valueOf(616));
		countryShortcut3ToCode.put("PRT", Integer.valueOf(620));
		countryShortcut3ToCode.put("PRI", Integer.valueOf(630));
		countryShortcut3ToCode.put("TWN", Integer.valueOf(158));
		countryShortcut3ToCode.put("COG", Integer.valueOf(178));
		countryShortcut3ToCode.put("REU", Integer.valueOf(638));
		countryShortcut3ToCode.put("RWA", Integer.valueOf(646));
		countryShortcut3ToCode.put("ROU", Integer.valueOf(642));
		countryShortcut3ToCode.put("RUS", Integer.valueOf(643));
		countryShortcut3ToCode.put("BLM", Integer.valueOf(652));
		countryShortcut3ToCode.put("MAF", Integer.valueOf(663));
		countryShortcut3ToCode.put("SLB", Integer.valueOf(90));
		countryShortcut3ToCode.put("ZMB", Integer.valueOf(894));
		countryShortcut3ToCode.put("WSM", Integer.valueOf(882));
		countryShortcut3ToCode.put("SMR", Integer.valueOf(674));
		countryShortcut3ToCode.put("STP", Integer.valueOf(678));
		countryShortcut3ToCode.put("SAU", Integer.valueOf(682));
		countryShortcut3ToCode.put("SWE", Integer.valueOf(752));
		countryShortcut3ToCode.put("CHE", Integer.valueOf(756));
		countryShortcut3ToCode.put("SEN", Integer.valueOf(686));
		countryShortcut3ToCode.put("SRB", Integer.valueOf(688));
		countryShortcut3ToCode.put("SYC", Integer.valueOf(690));
		countryShortcut3ToCode.put("SLE", Integer.valueOf(694));
		countryShortcut3ToCode.put("ZWE", Integer.valueOf(716));
		countryShortcut3ToCode.put("SGP", Integer.valueOf(702));
		countryShortcut3ToCode.put("SVK", Integer.valueOf(703));
		countryShortcut3ToCode.put("SVN", Integer.valueOf(705));
		countryShortcut3ToCode.put("SOM", Integer.valueOf(706));
		countryShortcut3ToCode.put("ESP", Integer.valueOf(724));
		countryShortcut3ToCode.put("LKA", Integer.valueOf(144));
		countryShortcut3ToCode.put("SHN", Integer.valueOf(654));
		countryShortcut3ToCode.put("KNA", Integer.valueOf(659));
		countryShortcut3ToCode.put("LCA", Integer.valueOf(662));
		countryShortcut3ToCode.put("SPM", Integer.valueOf(666));
		countryShortcut3ToCode.put("VCT", Integer.valueOf(670));
		countryShortcut3ToCode.put("ZAF", Integer.valueOf(710));
		countryShortcut3ToCode.put("SDN", Integer.valueOf(736));
		countryShortcut3ToCode.put("SGS", Integer.valueOf(239));
		countryShortcut3ToCode.put("SUR", Integer.valueOf(740));
		countryShortcut3ToCode.put("SJM", Integer.valueOf(744));
		countryShortcut3ToCode.put("SWZ", Integer.valueOf(748));
		countryShortcut3ToCode.put("SYR", Integer.valueOf(760));
		countryShortcut3ToCode.put("TJK", Integer.valueOf(762));
		countryShortcut3ToCode.put("TZA", Integer.valueOf(834));
		countryShortcut3ToCode.put("THA", Integer.valueOf(764));
		countryShortcut3ToCode.put("TGO", Integer.valueOf(768));
		countryShortcut3ToCode.put("TKL", Integer.valueOf(772));
		countryShortcut3ToCode.put("TON", Integer.valueOf(776));
		countryShortcut3ToCode.put("TTO", Integer.valueOf(780));
		countryShortcut3ToCode.put("TCD", Integer.valueOf(148));
		countryShortcut3ToCode.put("CZE", Integer.valueOf(203));
		countryShortcut3ToCode.put("TUN", Integer.valueOf(788));
		countryShortcut3ToCode.put("TUR", Integer.valueOf(792));
		countryShortcut3ToCode.put("TKM", Integer.valueOf(795));
		countryShortcut3ToCode.put("TCA", Integer.valueOf(796));
		countryShortcut3ToCode.put("TUV", Integer.valueOf(798));
		countryShortcut3ToCode.put("UGA", Integer.valueOf(800));
		countryShortcut3ToCode.put("UKR", Integer.valueOf(804));
		countryShortcut3ToCode.put("HUN", Integer.valueOf(348));
		countryShortcut3ToCode.put("UMI", Integer.valueOf(581));
		countryShortcut3ToCode.put("URY", Integer.valueOf(858));
		countryShortcut3ToCode.put("UZB", Integer.valueOf(860));
		countryShortcut3ToCode.put("VUT", Integer.valueOf(548));
		countryShortcut3ToCode.put("VAT", Integer.valueOf(336));
		countryShortcut3ToCode.put("VEN", Integer.valueOf(862));
		countryShortcut3ToCode.put("ARE", Integer.valueOf(784));
		countryShortcut3ToCode.put("USA", Integer.valueOf(840));
		countryShortcut3ToCode.put("GBR", Integer.valueOf(826));
		countryShortcut3ToCode.put("VNM", Integer.valueOf(704));
		countryShortcut3ToCode.put("WLF", Integer.valueOf(876));
		countryShortcut3ToCode.put("CXR", Integer.valueOf(162));
		countryShortcut3ToCode.put("ESH", Integer.valueOf(732));
		countryShortcut3ToCode.put("CAF", Integer.valueOf(140));
		countryShortcut3ToCode.put("CYP", Integer.valueOf(196));
	}

	/** Determine country name from ISO country code.
	 * @param countryCode ISO code of country
	 * @param languageShortcut in which language should the name be returned, e.g. "de" for german name
	 * @return country name of ISO country code or null if not found !
	 */
	static public String getNameFromCode(Integer countryCode, String languageShortcut) {
		String langName = null;

		if ("de".equals(languageShortcut)) {
			langName = countryCodelist_de.get(countryCode);
		} else if ("en".equals(languageShortcut)) {
			langName = countryCodelist_en.get(countryCode);			
		}

		return langName;
	}

	/** Determine country name from ISO ALPHA 2 country code.
	 * @param countryShortcut2 ISO code of country
	 * @param languageShortcut in which language should the name be returned, e.g. "de" for german name
	 * @return country name of ISO country code or null if not found !
	 */
	static public String getNameFromShortcut2(String countryShortcut2, String languageShortcut) {
		return UtilsCountryCodelist.getNameFromCode(UtilsCountryCodelist.getCodeFromShortcut2(countryShortcut2), languageShortcut);
	}
	
	
	/** Determine 2 letter country shortcut (e.g. "DE", "GB" ...") from ISO country code.
	 * @param countryCode ISO code of country
	 * @return country shortcut or null if not found
	 */
	static public String getShortcut2FromCode(Integer countryCode) {
		String shortcut = null;

		for (Map.Entry<String, Integer> entry : countryShortcut2ToCode.entrySet()) {
			if (entry.getValue().equals(countryCode)) {
				shortcut = entry.getKey();
				// specials
				if (shortcut.equals("UK")) {
					shortcut = "GB";
				}
				break;
			}
		}
		return shortcut;
	}

	/** Determine 3 letter country shortcut (e.g. "DEU", "GBR" ...") from ISO country code.
	 * @param countryCode ISO code of country
	 * @return country shortcut or null if not found
	 */
	static public String getShortcut3FromCode(Integer countryCode) {
		String shortcut = null;

		for (Map.Entry<String, Integer> entry : countryShortcut3ToCode.entrySet()) {
			if (entry.getValue().equals(countryCode)) {
				shortcut = entry.getKey();
				break;
			}
		}
		return shortcut;
	}

	/** Determine ISO country code from 2 letter ISO country shortcut (e.g. "DE", "GB" ...").
	 * @param countryShortcut2 2 letter ISO country shortcut (e.g. "DE", "GB" ...")
	 * @return ISO country code or null if not found
	 */
	static public Integer getCodeFromShortcut2(String countryShortcut2) {
		return countryShortcut2ToCode.get(countryShortcut2);
	}


	/** Determine ISO country code from 3 letter ISO country shortcut (e.g. "DEU", "GBR" ...").
	 * @param countryShortcut3 3 letter ISO country shortcut (e.g. "DEU", "GBR" ...")
	 * @return ISO country code or null if not found
	 */
	static public Integer getCodeFromShortcut3(String countryShortcut3) {
		return countryShortcut3ToCode.get(countryShortcut3);
	}
}
